In [2]:
import numpy as np

In [2]:
dizi=np.array([0,1,2,3,4])
dizi

array([0, 1, 2, 3, 4])

In [19]:
yas_dizi = np.array([18, 25, 22, 34, 26, 27, 19, 28, 30, 24])
boy_dizi = np.array([1.81, 1.67, 1.71, 1.89, 1.79, 1.75, 1.80, 1.78, 1.89, 1.82])
agirlik_dizi = np.array([81, 72, 74, 88, 82, 77, 78, 70, 90, 85])

In [20]:
print(yas_dizi.shape)
print(boy_dizi.shape)
print(agirlik_dizi.shape)

(10,)
(10,)
(10,)


In [8]:
listem=["Ali",13,True]
dizi=np.array(listem)
print(dizi)

['Ali' '13' 'True']


In [10]:
listem=[13,True]
dizi=np.array(listem)
print(dizi)

[13  1]


In [11]:
dizi=np.array([0,1,2,3])
dizi[2:]=[5,4]
print(dizi)

[0 1 5 4]


In [12]:
dizi=np.array([0,1,2,3])
dizi[2:]=[8]
print(dizi)

[0 1 8 8]


In [15]:
dizi=np.array([0,1,2,3])
np.append(dizi,(7,8,9))

array([0, 1, 2, 3, 7, 8, 9])

In [3]:
w=np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
basketbol_takimi = np.array([[18, 25, 22, 34, 26, 27, 19, 28, 30, 24],
                             [1.81, 1.67, 1.71, 1.89, 1.79, 1.75, 1.80, 1.78, 1.89, 1.82],
                             [81, 72, 74, 88, 82, 77, 78, 70, 90, 85]])
print(basketbol_takimi)
print(basketbol_takimi.shape)

[[18.   25.   22.   34.   26.   27.   19.   28.   30.   24.  ]
 [ 1.81  1.67  1.71  1.89  1.79  1.75  1.8   1.78  1.89  1.82]
 [81.   72.   74.   88.   82.   77.   78.   70.   90.   85.  ]]
(3, 10)


In [6]:
y=np.arange(8).reshape(2,4)
y

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
basketbol_takimi[0,3]

34.0

In [8]:
basketbol_takimi[0][3]

34.0

In [9]:
basketbol_takimi[0,]

array([18., 25., 22., 34., 26., 27., 19., 28., 30., 24.])

In [10]:
basketbol_takimi[0]

array([18., 25., 22., 34., 26., 27., 19., 28., 30., 24.])

In [12]:
basketbol_takimi[:,3]

array([34.  ,  1.89, 88.  ])

In [13]:
basketbol_takimi[0:2,3:7]

array([[34.  , 26.  , 27.  , 19.  ],
       [ 1.89,  1.79,  1.75,  1.8 ]])

In [15]:
dizi1=np.array([[0,1,2,3],[4,5,6,7]])
dizi2=dizi1*2
print(dizi2)

[[ 0  2  4  6]
 [ 8 10 12 14]]


In [16]:
dizi1=np.array([0,1,2,3])
dizi2=np.array([2,4,6,8])
print(dizi1*dizi2)


[ 0  4 12 24]


In [17]:
print(dizi1+dizi2)

[ 2  5  8 11]


In [22]:
vki=agirlik_dizi/boy_dizi**2
vki

array([24.72452001, 25.81663021, 25.30693205, 24.63536855, 25.59220998,
       25.14285714, 24.07407407, 22.09317005, 25.19526329, 25.66115203])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [27]:
np.linspace(0,20,9)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
x=np.array([0,1,2,3])
print(np.square(x))

[0 1 4 9]


In [31]:
print(np.sqrt(x))

[0.         1.         1.41421356 1.73205081]


In [32]:
print(np.cos(x))
print(np.sin(x))
print(np.tan(x))

[ 1.          0.54030231 -0.41614684 -0.9899925 ]
[0.         0.84147098 0.90929743 0.14112001]
[ 0.          1.55740772 -2.18503986 -0.14254654]


In [33]:
print(np.max(yas_dizi))
print(np.max(boy_dizi))
print(np.max(agirlik_dizi))

34
1.89
90


In [34]:
print(np.min(yas_dizi))
print(np.min(boy_dizi))
print(np.min(agirlik_dizi))

18
1.67
70


In [35]:
print(np.mean(yas_dizi))
print(np.mean(boy_dizi))
print(np.mean(agirlik_dizi))

25.3
1.791
79.7


In [36]:
print(np.std(yas_dizi))
print(np.std(boy_dizi))
print(np.std(agirlik_dizi))

4.627094120503711
0.06624952830020753
6.372597586541928
